---
title: "movies"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(caret)
library(MASS)
library(plotly)
library(ggfortify)
library(dplyr)
library(plotly)
library(reshape2)
library(readr)
library(dplyr)
```

```{r}
movies = read_csv("movies.csv")
genomes<-read_csv("MovieGenome.csv")
tags<-read_csv("genome-tags.csv")
ratings<-read_csv("ratings.csv")

```

```{r}
genome.pca = prcomp(genomes[,2:1129], scale.=FALSE,center = FALSE)
```

```{r}
######
##Plotting proportion of variance explained
pca_var = genome.pca$sdev^2
prop_varex <- pca_var/sum(pca_var) #Proportion of variance

plot(cumsum(prop_varex),type='b') #Cumulative proportion of variance

```


```{r}
pca_df<-data.frame(movieId=genomes$movieId,genome.pca$x[,1:500])

```

79357: Mr Nobody (2009)
```{r}

distances<-numeric(10381)

pca_dist<-pca_df[,2:500]


pca_df[match(79357,pca_df$movieId),]

myMovieRow<-pca_dist[9100,]


for(i in 1:10381){
  
  df<-data.frame()
  df = rbind(myMovieRow,pca_dist[i,])
  d=dist(df,method="euclidian")
  
  distances[i]=d
}


```

```{r}
dist_df<-data.frame(movieId=pca_df$movieId,distances)

dist_df<-dist_df[order(dist_df$distances),]

top3<-dist_df[2:4,]
bottom3<-dist_df[10379:10381,]
```

```{r}
movies[match(53464,movies$movieId),]
```



Top 3 movies:

1) id 48043: Fountain,The (2006)
2) id 4975: Vanilla Sky (1982)
3) id 89039: Another Earth (2011)

Bottom 3 movies:

1) id 5254:  Blade II (2002)
2) id 51007: Days of Glory (Indigènes) (2006)
3) id 53464: Fantastic Four: Rise of the Silver Surfer (2007)


Movie id of Mr. Nobody: 79357
```{r}
movieRatings<-ratings[which(ratings$movieId==79357),]
myRatingsCsv<-write.csv(movieRatings,"movieRatings.csv")
```

```{r}
myRatings<-read.csv("movieRatings.csv")

```

5)

```{r}
global_avg_rating<-sum(myRatings$rating)/973
each_userDf<-ratings%>%group_by(userId)%>%summarize(avg_rating=sum(rating)/n())
```


```{r}

kEstimate<-function(df,k){
  
  k_user_ratings<-numeric(k)
  
  for(i in 2:k){    #start from 2 as 1 is our movie itself
    
    movie<-df$movieId[k]
    print(movie)
    user_movies<-ratings[match(df$userId,ratings$userId),]
    print(user_movies)
    movie_row<-user_movies[match(movie,user_movies$movieId),]
    print(movie_row)
    
    users_rating<-movie_row$rating
    k_user_ratings<-c(k_user_ratings,users_rating)
  }  
  
  mean = sum(k_user_ratings)/k
  return(mean)
  
  #mean = sum(df$distance[1:k+1])/k  #k+1 because the first one is the movie itself
  
  #return(mean)
}

```

```{r}

for(i in 1:973){
  
  kEstimate(dist_df,1)
  
}

knn_rating

```





